change sol from tracker to control
	get rid of all recording features
	2 layer control scheme
		duplicate control on either side, load clips to separate layers
DONE move from pygame midi -> osc,
	so just assuming osc midi messages are coming in (from vvvv)

DONE fix looping/timeline control
	NAH	... probably think of better way to do whole dual-layers thing :/

midi control is broken af...

	fix l/r mixup.... rly need a way to figure out a nicer way 

successfully loaded ./savedata/beast
loop_type_l failed to load
clip_random_l failed to load
clip_clear_l failed to load
clip_random_r failed to load
qp_delete_l failed to load
clip_pause_r failed to load
col_go_l failed to load
loop_i/o_l failed to load
clip_clear_r failed to load
col_go_r failed to load
clip_pause_l failed to load
lp_select_l failed to load
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
----------------------------------------
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
----------------------------------------
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53055)
Traceback (most recent call last):
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Leo\Anaconda3\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 92, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "C:\Users\Leo\Anaconda3\lib\site-packages\pythonosc\osc_server.py", line 75, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 216, in osc2midi
    self.key_to_fun[key](n)
  File "C:\Users\Leo\Documents\GitHub\sol\midi_control.py", line 176, in funtor
    fun()
  File "C:\Users\Leo\Documents\GitHub\sol\sol_backend.py", line 313, in fun_tor
    clip.vars['playdir'] = direction
AttributeError: 'list' object has no attribute 'vars'
----------------------------------------
successfully saved ./savedata/beast
[Finished in 212.0s]